import CustomStyles from "@/styles/CustomStyles";

const MenuStyles = {
  container: {
    padding: "0 30px",
  },
  containerMenu: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))",
    gap: 20,
    justifyItems: "center",
    alignItems: "center",
    marginTop: 30,
  },
  menuButton: {
    ...CustomStyles.fontSub16,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-end",
    width: 140,
    height: 164,
    backgroundSize: "cover",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "center",
    color: CustomStyles.primaryBlack,
    borderRadius: 16,
    border: "none",
    cursor: "pointer",
  },
  menuButtonTextContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "30%",
    backgroundColor: CustomStyles.primaryBlue,
    color: CustomStyles.primaryWhite,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCart: {
    ...CustomStyles.fontHead16,
    position: "fixed",
    bottom: 80,
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: CustomStyles.primaryBlue,
    color: CustomStyles.primaryWhite,
    padding: "10px",
    borderRadius: "24px",
    zIndex: 100,
  },
};

export default MenuStyles;
